import { API_APIKEY,API_AUTHDOMAIN,API_DATABASEURL,API_PROJECTID,API_STORAGEBUCKET,API_MESSAGINGSENDERID,API_APPID,API_MEASUREMENTID} from '@env';

export default { 
    API_APIKEY,
    API_AUTHDOMAIN,
    API_DATABASEURL,
    API_PROJECTID,
    API_STORAGEBUCKET,
    API_MESSAGINGSENDERID,
    API_APPID,
    API_MEASUREMENTID
}